# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool: my-personal-computer


jobs:
- job: Build
  displayName: Build
  pool: my-personal-computer
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      npm install -g @angular/cli
      npm install
      ng build --prod
    displayName: 'npm install and build'
    
  - script: |
      npm config set registry http://registry.npmjs.org
      npm publish --access=public
    displayName: Publish to public

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
    displayName: Publish Artifact

- job: SAST_Scan
  displayName: SAST Scan
  pool: my-personal-computer
  